# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.12

# Get the latest stable version of Node 0.STABLE.latest
install:
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test
